### ISSUE TITLE
Depend on wasm-pack as a library rather than a CLI tool

### ISSUE THREAD

**Issue by JWorthe** [panoptix-za/web-bundler#1]
We currently depend on the wasm-pack CLI because of how this tool evolved from a build script. However, as a build.rs library, would make setup easier if we used wasm-pack as a library instead.

This looks like the entrypoint that should be used: https://docs.rs/wasm-pack/0.9.1/wasm_pack/command/build/index.html

**Comment by stephanbuys** [comment]
Much cleaner

Sent from a mobile device.

On 07 Jan 2021, at 11:51, Justin Wernick <notifications@github.com> wrote:

﻿

We currently depend on the wasm-pack CLI because of how this tool evolved from a build script. However, as a build.rs library, would make setup easier if we used wasm-pack as a library instead.

This looks like the entrypoint that should be used: https://docs.rs/wasm-pack/0.9.1/wasm_pack/command/build/index.html
